// Builds the God view website into dist/ (or the folder given as the first
// argument): the pages in src/, MapLibre GL JS, and config.mjs naming the
// IndangGO API the site reads.
//
//   GOD_VIEW_API_URL=https://indang-trike-app.onrender.com npm run build
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DEFAULT_API_URL = 'https://indang-trike-app.onrender.com';
const MAP_ASSETS = ['maplibre-gl.mjs', 'maplibre-gl-shared.mjs', 'maplibre-gl-worker.mjs', 'maplibre-gl.css'];
const LOCAL_HOSTS = new Set(['localhost', '127.0.0.1']);

export function buildSite(out, apiUrl = process.env.GOD_VIEW_API_URL || DEFAULT_API_URL) {
  const api = new URL(apiUrl);
  // Admins type their password into this site, so it may only send it over
  // HTTPS, or to a server on this computer during development.
  if (api.protocol !== 'https:' && !(api.protocol === 'http:' && LOCAL_HOSTS.has(api.hostname))) {
    throw new Error(`GOD_VIEW_API_URL must be an https:// address (got ${apiUrl}).`);
  }
  const root = path.dirname(fileURLToPath(import.meta.url));
  const require = createRequire(import.meta.url);
  const mapDist = path.join(path.dirname(require.resolve('maplibre-gl/package.json')), 'dist');

  rmSync(out, { recursive: true, force: true });
  cpSync(path.join(root, 'src'), out, { recursive: true });
  mkdirSync(path.join(out, 'vendor'));
  for (const asset of MAP_ASSETS) cpSync(path.join(mapDist, asset), path.join(out, 'vendor', asset));
  writeFileSync(path.join(out, 'config.mjs'), `// Generated by build.mjs: the IndangGO API this site reads.\nexport const API_BASE_URL = ${JSON.stringify(api.origin)};\n`);
  // The page's Content-Security-Policy lets it connect to exactly this API.
  const page = path.join(out, 'index.html');
  writeFileSync(page, readFileSync(page, 'utf8').replaceAll('__API_ORIGIN__', api.origin));
  return api.origin;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = path.resolve(process.argv[2] ?? path.join(path.dirname(fileURLToPath(import.meta.url)), 'dist'));
  try {
    console.log(`God view built in ${out} for ${buildSite(out)}`);
  } catch (error) {
    console.error(`build: ${error.message}`);
    process.exitCode = 1;
  }
}
